### ISSUE TITLE
Exit code 2 with the README code

### ISSUE THREAD

**Issue by TrevorBramble** [d4l3k/go-pry#1]
Just made a `foo.go` to try this out after getting and installing `go-pry`:
```
package main

import "github.com/d4l3k/go-pry/pry"

func main() {
	a := 1
	pry.Pry()
}
```
But this is the result:
![image](https://cloud.githubusercontent.com/assets/92880/6863667/c2753a48-d412-11e4-9822-884cbf313aa4.png)

**Comment by trevrosen** [comment]
+1

**Comment by TrevorBramble** [comment]
@trevrosen Nice work!

**Comment by trevrosen** [comment]
@TrevorBramble thanks! Glad this all-Trevor ticket got resolved. :smiley_cat:
