### ISSUE TITLE
cannot find package "golang.org/x/tools/go/gcimporter"

### ISSUE THREAD

**Issue by daino3** [d4l3k/go-pry#12]
Hello. Fetching the project fails for me running:
```
go get "github.com/d4l3k/go-pry/pry"
```

with:
```
package golang.org/x/tools/go/gcimporter: cannot find package "golang.org/x/tools/go/gcimporter" in any of:
	/usr/local/go/src/golang.org/x/tools/go/gcimporter (from $GOROOT)
	/home/vagrant/go/src/golang.org/x/tools/go/gcimporter (from $GOPATH)
```

However, `/home/vagrant/go/src/golang.org/x/tools/go` has `gcimporter15` directory

Symlinking gcimporter15 to gcimporter results in:

```
no buildable Go source files in /home/vagrant/go/src/golang.org/x/tools/go/types
```

Which is true - there's an additional directory `typeutil`

I'm using go1.6 darwin/amd64 - has the dependency structure changed for go-1.6?

**Comment by igs-awilliams** [comment]
Experiencing the exact same issue/error on Ubuntu Linux 14.04.4 and OSX 10.11.4 both running go 1.6.2 linux/amd64 and 1.6.2 darwin/amd64 respectively.

**Comment by d4l3k** [comment]
Looks like some packages were moved around for go1.6. I just pushed a commit that should fix it.

**Comment by st0012** [comment]
@d4l3k Hi I just got the same error. I use Go 1.8.1
