### ISSUE TITLE
duplicate key in map literals

### ISSUE THREAD

**Issue by mooreniemi** [d4l3k/go-pry#13]
First off: thanks so much for this project! I love `pry`.

I am a bit of a newbie to golang, so it is totally possible I have set things up wrong. Here's my experience trying to use `go-pry` on my project [vessel](https://github.com/mooreniemi/vessel) (`./main.go:50` is where I'm calling `pry.Pry()`):

```
Ansible:~/Documents/Code/golang/src/vessel/ master ⌂ go-pry run main.go
# command-line-arguments
./main.go:50: undefined: parser in parser.ParseVesselMap
./main.go:50: undefined: parser in parser.VesselMapAsInts
./main.go:50: undefined: parser in parser.ParseVesselYaml
./main.go:50: undefined: viewcomponents in viewcomponents.UpdateTimer
./main.go:50: undefined: viewcomponents in viewcomponents.CleanUp
./main.go:50: undefined: viewcomponents in viewcomponents.VisorView
./main.go:50: undefined: viewcomponents in viewcomponents.VesselMap
./main.go:50: undefined: viewcomponents in viewcomponents.ChamberMenu
./main.go:50: undefined: goncurses in goncurses.Below
./main.go:50: undefined: goncurses
./main.go:50: too many errors
Reverting files
```

It could be an incidental effect of the log order, but it appears all of the packages failing to be imported are non-stdlib ones I'm grabbing via github.

Let me know if I can get you any other information, or feel free to point me to the general area of the code I might be able to tinker with to get a solution. Always happier to give a PR than an issue. :)

**Comment by mooreniemi** [comment]
I think the above was a result of me using internal packages, which I've learned is a newbie mistake. Sorry for that. Now it looks like I am encountering something else:

```
go-pry run cmd/vessel/main.go
# command-line-arguments
cmd/vessel/main.go:48: duplicate key "vessel" in map literal
cmd/vessel/main.go:48: vessel.UpdateTimer undefined (type vessel.Vessel has no field or method UpdateTimer)
cmd/vessel/main.go:48: vessel.CleanUp undefined (type vessel.Vessel has no field or method CleanUp)
cmd/vessel/main.go:48: vessel.VisorView undefined (type vessel.Vessel has no field or method VisorView)
cmd/vessel/main.go:48: vessel.MapView undefined (type vessel.Vessel has no field or method MapView)
cmd/vessel/main.go:48: vessel.ChamberMenu undefined (type vessel.Vessel has no field or method ChamberMenu)
cmd/vessel/main.go:48: vessel.Octopus undefined (type vessel.Vessel has no field or method Octopus)
cmd/vessel/main.go:48: vessel.Bird undefined (type vessel.Vessel has no field or method Bird)
cmd/vessel/main.go:48: vessel.RandomArt undefined (type vessel.Vessel has no field or method RandomArt)
cmd/vessel/main.go:48: vessel.ArtByID undefined (type vessel.Vessel has no field or method ArtByID)
cmd/vessel/main.go:48: too many errors
Reverting files
```

Perhaps still a result of my bad code organization?

**Comment by d4l3k** [comment]
Not entirely sure, I'll take a closer look tonight or tomorrow.

**Comment by d4l3k** [comment]
Sorry for getting back to this so late, slipped my mind entirely until I got another bug report on this repo.

Previously package aliases weren't added. I've added a very basic reproduction case under `example/packagealiases` and it should work now.

Let me know if it's still a problem!
