### ISSUE TITLE
"For" statement not recognized

### ISSUE THREAD

**Issue by robfig** [d4l3k/go-pry#2]
Cool project.  Seems like it doesn't recognize for loops, though (not sure if you expect it to work or not)
```
$ cat src/pry-test/main.go
package main

import "github.com/d4l3k/go-pry/pry"

func main() {
	for i := 0; i < 10; i++ {
		i++
		pry.Pry()
	}
}

$ go-pry src/pry-test/main.go
Prying into  src/pry-test/main.go
[0x2082cc810]
Unknown *ast.ForStmt
```

**Comment by d4l3k** [comment]
Since Go is a compiled language it isn't possible to use Go to evaluate arbitrary statements. Thus, I've been implementing a Go interpreter but it's not feature complete.

I'll implement this later today.

**Comment by d4l3k** [comment]
This code now works:
https://github.com/d4l3k/go-pry/blob/master/example/for-loop.go
