### ISSUE TITLE
[bug] after running the go-pry, terminal changed

### ISSUE THREAD

**Issue by jsvisa** [d4l3k/go-pry#21]
After exit the go-pry, any  input into the terminal doesn't dis displays. 

OS: Ubuntu 16.04
Golang: 1.8.3

**Comment by d4l3k** [comment]
How did the terminal change?

Please provide as much info as you can including:
* Screenshots
* Description of what changed
* Terminal emulator + version
* OS + version
* Go version

**Comment by d4l3k** [comment]
What terminal are you using? The default one?

**Comment by jsvisa** [comment]
Iterm2 + tmux or the default one the same issue

**Comment by d4l3k** [comment]
ITerm2 is for OSX not Ubuntu as far as I'm aware. What's the exact steps you take to reproduce (including sshing, tmux etc)?

**Comment by jsvisa** [comment]
Sorry, 

I'm running Ubuntu by vagrant on Mac OSX, and ssh into the Ubuntu, then runing `go-pry` 

see the screenshot for detail

![a](https://user-images.githubusercontent.com/3627395/28195739-b926fab8-6811-11e7-8317-bb399d750b5c.gif)

**Comment by elisarver** [comment]
I had to `stty sane` then `^L` to get visible user input back.

**Comment by whoisjake** [comment]
macOS Sierra - Terminal - bash 4.4.12(1)-release

Run go pry, exit out, no visible characters. Noticed that the output from whatever command starts on the same line.

![screen shot 2017-07-14 at 9 24 12 am](https://user-images.githubusercontent.com/2079/28216174-4c6c39aa-6876-11e7-8a8d-d1febda6583f.png)

**Comment by d4l3k** [comment]
I think this happened because #18 didn't properly close the tty. cc @mattn

**Comment by mattn** [comment]
Ooops. Sorry :(

**Comment by whoisjake** [comment]
confirmed works!

![screen shot 2017-07-14 at 1 09 41 pm](https://user-images.githubusercontent.com/2079/28224705-c64804a6-6895-11e7-97a7-7718db2e383c.png)
