### ISSUE TITLE
Installation of go-pry

### ISSUE THREAD

**Issue by jeffreyyong** [d4l3k/go-pry#42]
I have followed the instructions and done all the necessary installation. However I got "go-pry: command not found" when I was trying to run the command `go-pry run main.go`

I am wondering if I am missing something? Thanks

**Comment by d4l3k** [comment]
Do you have $GOPATH/bin in your path?

https://golang.org/doc/code.html#GOPATH
> For convenience, add the workspace's bin subdirectory to your PATH:
> ```
> $ export PATH=$PATH:$(go env GOPATH)/bin
> ```

**Comment by gerrywastaken** [comment]
Thank you. :)
