### ISSUE TITLE
How to use go-pry in chrome ?

### ISSUE THREAD

**Issue by worldofprasanna** [d4l3k/go-pry#70]
I tried to find docs to know how to setup go-pry in chrome but I couldn't find any. Can you please let me know the setup steps for it ?

Thanks.

**Comment by d4l3k** [comment]
Do you mean the web version? https://gopry.rice.sh/

**Comment by worldofprasanna** [comment]
Yes .. I was trying to setup one for me like that

**Comment by d4l3k** [comment]
Ah, got it! It's still a bit rough but there's two ways to do it. One is
via generating the static files in a similar way to
https://github.com/d4l3k/go-pry/blob/master/playground/Makefile#L9

The other is to run the docker container which will auto generate those
bundles.

**Comment by worldofprasanna** [comment]
Oh ok @d4l3k .. Thanks. 
And BTW, this is a very useful tool 👍
